In [14]:
df.to_csv("../data/ecommerce_sales_cleaned.csv", index=False)

In [13]:
df["Revenue"].describe()

count    500.000000
mean      60.438920
std       57.129889
min        5.100000
25%       22.725000
50%       40.380000
75%       72.050000
max      275.000000
Name: Revenue, dtype: float64

In [12]:
df["Revenue"] = (
    df["Quantity"]
    * df["Unit_Price"]
    * (1 - df["Discount"])
)

df["Revenue"] = df["Revenue"].round(2)

df.head()

,Order_ID,Order_Date,Customer_ID,City,Product,Category,Quantity,Unit_Price,Discount,Payment_Method,Revenue
0,ORD0062,2026-01-01,C096,Negombo,Planner,Stationery,2,10.0,0.10,Credit Card,18.00
1,ORD0461,2026-01-01,C127,Jaffna,Marker Set,Stationery,5,7.5,0.15,Cash on Delivery,31.88
2,ORD0146,2026-01-01,C057,Kurunegala,Water Bottle,Home & Living,4,12.0,0.00,Cash on Delivery,48.00
3,ORD0221,2026-01-01,C131,Kandy,Pen Set,Stationery,3,8.5,0.00,Digital Wallet,25.50
4,ORD0033,2026-01-02,C113,Colombo,Coffee Mug,Home & Living,1,9.5,0.05,Digital Wallet,9.02

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        500 non-null    object
 1   Order_Date      500 non-null    datetime64[ns]
 2   Customer_ID     500 non-null    object
 3   City            500 non-null    object
 4   Product         500 non-null    object
 5   Category        500 non-null    object
 6   Quantity        500 non-null    int64
 7   Unit_Price      500 non-null    float64
 8   Discount        500 non-null    float64
 9   Payment_Method  500 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(1), object(6)
memory usage: 43.0+ KB

In [10]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [9]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
City              0
Product           0
Category          0
Quantity          0
Unit_Price        0
Discount          0
Payment_Method    0
dtype: int64

In [8]:
df["City"] = df["City"].fillna("Unknown")

In [7]:
df[df["City"].isnull()]

,Order_ID,Order_Date,Customer_ID,City,Product,Category,Quantity,Unit_Price,Discount,Payment_Method
17,ORD0359,2026-01-04,C090,NaN,Mechanical Keyboard,Electronics,5,55.0,0.10,Cash on Delivery
30,ORD0382,2026-01-08,C129,NaN,Cap,Fashion,2,11.0,0.00,Digital Wallet
36,ORD0321,2026-01-10,C097,NaN,Mechanical Keyboard,Electronics,4,55.0,0.00,Debit Card
134,ORD0498,2026-02-14,C138,NaN,Backpack,Fashion,1,38.0,0.10,Cash on Delivery
235,ORD0367,2026-03-23,C021,NaN,Coffee Mug,Home & Living,1,9.5,0.05,Cash on Delivery
299,ORD0052,2026-04-18,C060,NaN,Notebook,Stationery,1,6.0,0.15,Cash on Delivery
300,ORD0267,2026-04-19,C083,NaN,Water Bottle,Home & Living,5,12.0,0.15,Credit Card
457,ORD0068,2026-06-13,C120,NaN,Mechanical Keyboard,Electronics,5,55.0,0.20,Credit Card

In [6]:
df = df.drop_duplicates()

df.shape

(500, 10)

In [5]:
df.duplicated().sum()

np.int64(3)

In [4]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
City              8
Product           0
Category          0
Quantity          0
Unit_Price        0
Discount          0
Payment_Method    0
dtype: int64

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        503 non-null    object
 1   Order_Date      503 non-null    object
 2   Customer_ID     503 non-null    object
 3   City            495 non-null    object
 4   Product         503 non-null    object
 5   Category        503 non-null    object
 6   Quantity        503 non-null    int64
 7   Unit_Price      503 non-null    float64
 8   Discount        503 non-null    float64
 9   Payment_Method  503 non-null    object
dtypes: float64(2), int64(1), object(7)
memory usage: 39.4+ KB

In [2]:
df.shape

(503, 10)

In [1]:
import pandas as pd

df = pd.read_csv("../data/ecommerce_sales_raw.csv")

df.head()

,Order_ID,Order_Date,Customer_ID,City,Product,Category,Quantity,Unit_Price,Discount,Payment_Method
0,ORD0062,2026-01-01,C096,Negombo,Planner,Stationery,2,10.0,0.10,Credit Card
1,ORD0461,2026-01-01,C127,Jaffna,Marker Set,Stationery,5,7.5,0.15,Cash on Delivery
2,ORD0146,2026-01-01,C057,Kurunegala,Water Bottle,Home & Living,4,12.0,0.00,Cash on Delivery
3,ORD0221,2026-01-01,C131,Kandy,Pen Set,Stationery,3,8.5,0.00,Digital Wallet
4,ORD0033,2026-01-02,C113,Colombo,Coffee Mug,Home & Living,1,9.5,0.05,Digital Wallet