In [12]:
query = """
SELECT
    ROUND(SUM(Revenue) / COUNT(DISTINCT Order_ID), 2)
    AS Average_Order_Value
FROM sales;
"""

pd.read_sql_query(query, conn)

   Average_Order_Value
0                60.44

In [11]:
query = """
SELECT
    Payment_Method,
    ROUND(SUM(Revenue), 2) AS Total_Revenue
FROM sales
GROUP BY Payment_Method
ORDER BY Total_Revenue DESC;
"""

pd.read_sql_query(query, conn)

     Payment_Method  Total_Revenue
0       Credit Card        9424.43
1    Digital Wallet        7392.27
2  Cash on Delivery        7032.01
3        Debit Card        6370.75

In [10]:
query = """
SELECT
    SUBSTR(Order_Date, 1, 7) AS Month,
    ROUND(SUM(Revenue), 2) AS Total_Revenue
FROM sales
GROUP BY Month
ORDER BY Month;
"""

pd.read_sql_query(query, conn)

     Month  Total_Revenue
0  2026-01        4585.59
1  2026-02        5302.38
2  2026-03        4541.55
3  2026-04        5992.24
4  2026-05        5848.61
5  2026-06        3949.09

In [9]:
query = """
SELECT
    Customer_ID,
    ROUND(SUM(Revenue), 2) AS Total_Revenue
FROM sales
GROUP BY Customer_ID
ORDER BY Total_Revenue DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

  Customer_ID  Total_Revenue
0        C147         713.50
1        C088         657.40
2        C012         585.75
3        C057         577.45
4        C149         552.70
5        C128         533.55
6        C113         513.22
7        C084         513.15
8        C026         472.55
9        C028         463.50

In [8]:
query = """
SELECT
    City,
    ROUND(SUM(Revenue), 2) AS Total_Revenue
FROM sales
GROUP BY City
ORDER BY Total_Revenue DESC;
"""

pd.read_sql_query(query, conn)

         City  Total_Revenue
0       Galle        5610.43
1     Colombo        5340.18
2       Kandy        5300.96
3      Jaffna        5089.77
4  Kurunegala        4835.68
5     Negombo        3233.62
6     Unknown         808.82

In [7]:
query = """
SELECT
    Product,
    SUM(Quantity) AS Total_Quantity_Sold
FROM sales
GROUP BY Product
ORDER BY Total_Quantity_Sold DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

               Product  Total_Quantity_Sold
0              T-Shirt                  113
1          Storage Box                  109
2         Water Bottle                  107
3  Mechanical Keyboard                  106
4           Marker Set                  105
5               Hoodie                  100
6           Coffee Mug                   99
7             Backpack                   97
8       Wireless Mouse                   93
9               Webcam                   90

In [6]:
query = """
SELECT
    Category,
    ROUND(SUM(Revenue), 2) AS Total_Revenue
FROM sales
GROUP BY Category
ORDER BY Total_Revenue DESC;
"""

pd.read_sql_query(query, conn)

        Category  Total_Revenue
0    Electronics       12809.86
1        Fashion        9781.20
2  Home & Living        5102.73
3     Stationery        2525.67

In [5]:
query = """
SELECT
    COUNT(DISTINCT Order_ID) AS Total_Orders,
    COUNT(DISTINCT Customer_ID) AS Total_Customers
FROM sales;
"""

pd.read_sql_query(query, conn)

   Total_Orders  Total_Customers
0           500              142

In [4]:
query = """
SELECT
    ROUND(SUM(Revenue), 2) AS Total_Revenue
FROM sales;
"""

pd.read_sql_query(query, conn)

   Total_Revenue
0       30219.46

In [3]:
query = """
SELECT *
FROM sales
LIMIT 5;
"""

pd.read_sql_query(query, conn)

,Order_ID,Order_Date,Customer_ID,City,Product,Category,Quantity,Unit_Price,Discount,Payment_Method,Revenue
0,ORD0062,2026-01-01,C096,Negombo,Planner,Stationery,2,10.0,0.10,Credit Card,18.00
1,ORD0461,2026-01-01,C127,Jaffna,Marker Set,Stationery,5,7.5,0.15,Cash on Delivery,31.88
2,ORD0146,2026-01-01,C057,Kurunegala,Water Bottle,Home & Living,4,12.0,0.00,Cash on Delivery,48.00
3,ORD0221,2026-01-01,C131,Kandy,Pen Set,Stationery,3,8.5,0.00,Digital Wallet,25.50
4,ORD0033,2026-01-02,C113,Colombo,Coffee Mug,Home & Living,1,9.5,0.05,Digital Wallet,9.02

In [2]:
import pandas as pd
import sqlite3

df = pd.read_csv("../data/ecommerce_sales_cleaned.csv")

conn = sqlite3.connect("../data/ecommerce_sales.db")

df.to_sql(
    "sales",
    conn,
    if_exists="replace",
    index=False
)

print("Database created successfully!")

Database created successfully!